services:
  flowtrix:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: flowtrix
    image: flowtrix:v0.0.1.26050601

    restart: always

    networks:
      - flowtrix-tier

    ports:
      - "3005:8080"

    env_file:
      - .env

    environment:
      ROOT_URL: http://localhost:3005
      PORT: 8080

      MONGO_URL: mongodb+srv://admin_db_user:UjckcEXbdcOtyyuw@dev.dyebs9o.mongodb.net/flowtrix?retryWrites=true&w=majority
      MONGO_OPLOG_URL: ""

      ACCOUNTS_EMAIL_VERIFICATION: false
      MAIL_URL: smtp://localhost:25

networks:
  flowtrix-tier:
    driver: bridge